package com.learning.atypon.spring.mvc.enums;

/**
 * @author Wajd Mihyar
 * @date 8/3/2021 12:11 PM
 */

//enum has all API Error codes
public enum ErrorCode {
    NO_ERROR(0),

    INTERNAL_SERVER_ERROR(1),

    INVALID_USER(101),

    INVALID_OTP(102),

    DEVICE_NOT_REGISTERED(103),

    ACCOUNT_LOCKED(104),

    PROFILE_NOT_ACTIVE(105),

    WRONG_USER_CREDENTIALS(106),

    REFRESH_TOKEN_EXPIRED(107),

    EXPIRED_PASSWORD(108),

    INVALID_DEBIT_CARD(109),

    DEVICE_LOCKED(110),

    PASSWORD_EXISTS_IN_HISTORY(111),

    INVALID_PASSWORD_FORMAT(112),

    WRONG_PASSWORD(113),

    TERMS_CONDITIONS_NOT_APPROVED(114),

    UPDATED_TERMS_CONDITIONS_NOT_APPROVED(115),

    FINGER_PRINT_EXPIRED(116),

    EXPIRED_OTP(117),

    PASSWORD_CURRENTLY_EXIST(118),

    TERMS_CONDITION_NOT_FOUND(119),

    DEVICE_NOT_BIOMETRIC_ACTIVE(120),

    INVALID_VALIDATION_UID(121),

    INCORRECT_DEBIT_CARD_PIN(125),

    NO_RESULT_FOUND(2),

    SUCCESS(200),

    INVALID_TRANSACTION_ID(201),

    INVALID_ACCOUNT_ID(203),

    INVALID_AMOUNT_TRANSFER(300),

    TRANSFERS_PER_DAY_EXCEEDED(301),

    TRANSFER_AMOUNT_PER_DAY_EXCEEDED(302),

    TRANSFERS_PER_MONTH_EXCEEDED(303),

    TRANSFER_AMOUNT_PER_MONTH_EXCEEDED(304),

    TRANSFER_AMOUNT_NOT_ALLOWED(305),

    INVALID_CUSTOMER_LOCATION(702),

    INVALID_BRANCH(703),

    INVALID_ATM(704),

    INVALID_SERVICE(705),

    INVALID_TRAVEL_MODE(706),

    INVALID_CITY_CODE(23),

    INVALID_CONTENT_ID(1501),

    INVALID_PAGE_NUMBER(9),

    INVALID_LOAN(1600),

    BENEFICIARY_EXISTS(500),

    INVALID_MOBILE_FORMAT(521),

    MISMATCH_CONFIRM_MOBILE_FORMAT(523),

    INVALID_CONFIRM_MOBILE_FORMAT(522),

    INVALID_NAME(504),

    INVALID_BENEFICIARY_ID(501),

    INVALID_BENEFICIARY_NAME(504),

    INVALID_ACCOUNT_NUMBER(16),

    INVALID_AMOUNT(307),

    INVALID_MOBILE_NUM(135),

    INVALID_VALIDATID(308),

    SECOND_FACTOR_AUTH_REQUIRED(63),

    INCORRECT_OTP(102),

    INVALID_NICKNAME(617),

    INVALID_BILLNUM(610),

    INVALID_BILLER_SERVICE(612),

    BILL_EXISTS(616),

    INVALID_BILLER_CODE(611),

    INVALID_PREPAID_CATEGORY(613),

    INVALID_BILLID(609),

    INVALID_Ben_NAME(513);

    private final int value;

    ErrorCode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
